# Generated by Django 5.2 on 2025-05-20 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloudysky", "0002_alter_post_hidden_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="hidden_reason",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="cloudysky.suppressionreason",
            ),
        ),
    ]
